import { ALL_INDIA_STATES, getStateById, getStateByName } from '../data/indiaStates';
import { IndiaState, StateDestination, StateAttraction } from '../types/indiaStates';

export interface IndianLocationResult {
  id: string;
  name: string;
  state: string;
  district_or_city: string;
  country: 'India';
  description: string;
  category:
    | 'City'
    | 'Historical & Heritage'
    | 'Mountains & Hill Stations'
    | 'Beaches & Coastal'
    | 'Wildlife & Nature'
    | 'Religious & Spiritual'
    | 'Adventure'
    | 'Food & Culture';
  subcategory: string;
  latitude: number;
  longitude: number;
  best_time_to_visit: string;
  recommended_duration: string;
  budget_category: 'Budget' | 'Mid-range' | 'Premium';
  travel_themes: string[];
  activities: string[];
  accessibility: 'Verified' | 'Available' | 'Unknown';
  nearby_destinations: string[];
  image: string;
  is_state_capital?: boolean;
}

// Known International queries to explicitly reject/filter out
export const KNOWN_INTERNATIONAL_KEYWORDS = [
  'paris',
  'france',
  'tokyo',
  'japan',
  'london',
  'uk',
  'united kingdom',
  'england',
  'rome',
  'italy',
  'bali',
  'indonesia',
  'bangkok',
  'thailand',
  'phuket',
  'singapore',
  'dubai',
  'uae',
  'new york',
  'usa',
  'united states',
  'america',
  'los angeles',
  'california',
  'switzerland',
  'zurich',
  'geneva',
  'sydney',
  'australia',
  'melbourne',
  'berlin',
  'germany',
  'amsterdam',
  'netherlands',
  'spain',
  'barcelona',
  'madrid',
  'maldives',
  'mauritius',
  'canada',
  'toronto',
  'vancouver',
  'turkey',
  'istanbul',
  'egypt',
  'cairo',
  'kyoto',
  'osaka',
  'seoul',
  'korea',
  'hong kong',
  'macau',
  'vietnam',
  'hanoi',
  'da nang',
  'greece',
  'athens',
  'santorini',
  'venice',
  'florence',
  'prague',
  'vienna',
  'austria',
];

/**
 * Validates if a location name, query string, or coords belong strictly to India.
 */
export function isIndianLocation(queryOrName: string, lat?: number, lng?: number): boolean {
  if (!queryOrName || !queryOrName.trim()) return false;
  const q = queryOrName.toLowerCase().trim();

  // Explicit check against international keywords
  for (const intl of KNOWN_INTERNATIONAL_KEYWORDS) {
    // If the query exactly matches or contains international keyword as a discrete word
    const regex = new RegExp(`\\b${intl}\\b`, 'i');
    if (regex.test(q)) {
      return false;
    }
  }

  // If geographic coordinates are provided, verify they fall within India bounding box
  // Lat: ~6.0° N to 38.0° N, Long: ~68.0° E to 98.0° E
  if (typeof lat === 'number' && typeof lng === 'number' && !isNaN(lat) && !isNaN(lng)) {
    const isWithinIndiaBox = lat >= 6.0 && lat <= 38.5 && lng >= 68.0 && lng <= 98.5;
    if (!isWithinIndiaBox) return false;
  }

  return true;
}

/**
 * Curated Comprehensive Indian Travel Reference Dataset
 * Covers all 28 States, 8 Union Territories, famous cities, heritage monuments,
 * hill stations, beaches, spiritual sanctuaries, nature reserves, and food hubs.
 */
export const CORE_INDIAN_DESTINATIONS: IndianLocationResult[] = [
  // --- NORTH INDIA ---
  {
    id: 'ind-del-01',
    name: 'Delhi',
    state: 'Delhi (NCT)',
    district_or_city: 'New Delhi / Central Delhi',
    country: 'India',
    description: 'The historic capital of India, bridging ancient Mughal sultanates, British colonial boulevards, and vibrant bustling food bazaars.',
    category: 'City',
    subcategory: 'National Capital & Historic Hub',
    latitude: 28.6139,
    longitude: 77.209,
    best_time_to_visit: 'October to March (Pleasant autumn & crisp winter)',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Historical', 'Food & Cuisine', 'Shopping', 'Cultural', 'Urban Life'],
    activities: ['Heritage walking tours', 'Old Delhi street food tasting', 'Museum exploration', 'Bazaar shopping'],
    accessibility: 'Verified',
    nearby_destinations: ['Agra', 'Jaipur', 'Neemrana', 'Mathura', 'Rishikesh'],
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-del-02',
    name: 'Taj Mahal',
    state: 'Uttar Pradesh',
    district_or_city: 'Agra',
    country: 'India',
    description: 'UNESCO World Heritage wonder of the world, built by Mughal Emperor Shah Jahan in pure white Makrana marble on the banks of Yamuna river.',
    category: 'Historical & Heritage',
    subcategory: 'World Heritage Wonder',
    latitude: 27.1751,
    longitude: 78.0421,
    best_time_to_visit: 'October to March',
    recommended_duration: '1 - 2 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Historical', 'Architecture', 'Romantic', 'Photography'],
    activities: ['Sunrise marble photography', 'Mughal garden walk', 'Petha tasting', 'Agra Fort exploration'],
    accessibility: 'Verified',
    nearby_destinations: ['Agra Fort', 'Fatehpur Sikri', 'Mathura', 'Delhi'],
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-del-03',
    name: 'Red Fort (Lal Qila)',
    state: 'Delhi (NCT)',
    district_or_city: 'Old Delhi',
    country: 'India',
    description: 'Iconic 17th-century Mughal red sandstone fortress commissioned by Shah Jahan, symbolizing India’s independence history and architectural grandeur.',
    category: 'Historical & Heritage',
    subcategory: 'Mughal Fortress',
    latitude: 28.6562,
    longitude: 77.241,
    best_time_to_visit: 'October to March',
    recommended_duration: '3 - 4 Hours',
    budget_category: 'Budget',
    travel_themes: ['Historical', 'Architecture', 'Heritage'],
    activities: ['Sound & Light show', 'Diwan-i-Aam visit', 'Chandni Chowk food walk'],
    accessibility: 'Verified',
    nearby_destinations: ['Jama Masjid', 'Chandni Chowk', 'Raj Ghat'],
    image: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-del-04',
    name: 'Qutub Minar',
    state: 'Delhi (NCT)',
    district_or_city: 'South Delhi / Mehrauli',
    country: 'India',
    description: 'The world’s tallest brick minaret standing at 72.5 meters, surrounded by ancient Indo-Islamic ruins and the rust-resistant 4th-century Iron Pillar.',
    category: 'Historical & Heritage',
    subcategory: 'UNESCO World Heritage Monument',
    latitude: 28.5244,
    longitude: 77.1855,
    best_time_to_visit: 'October to March',
    recommended_duration: '2 - 3 Hours',
    budget_category: 'Budget',
    travel_themes: ['Historical', 'Architecture', 'Archaeology'],
    activities: ['Architectural photography', 'Mehrauli Archaeological Park trail'],
    accessibility: 'Verified',
    nearby_destinations: ['Hauz Khas Village', 'Lotus Temple', 'Lodhi Garden'],
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-del-05',
    name: 'India Gate',
    state: 'Delhi (NCT)',
    district_or_city: 'Central Delhi',
    country: 'India',
    description: 'Grand 42-meter memorial triumphal arch situated on the ceremonial Kartavya Path, glowing spectacularly during evening illuminations.',
    category: 'Historical & Heritage',
    subcategory: 'National Memorial Arch',
    latitude: 28.6129,
    longitude: 77.2295,
    best_time_to_visit: 'Evening all year round (Best Oct - Mar)',
    recommended_duration: '1 - 2 Hours',
    budget_category: 'Budget',
    travel_themes: ['Historical', 'Public Square', 'Evening Leisure'],
    activities: ['Evening stroll', 'Boating on lawns', 'Ice cream tasting', 'National War Memorial visit'],
    accessibility: 'Verified',
    nearby_destinations: ['Rashtrapati Bhavan', 'National Gallery of Modern Art', 'Connaught Place'],
    image: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-up-01',
    name: 'Varanasi (Kashi / Banaras)',
    state: 'Uttar Pradesh',
    district_or_city: 'Varanasi',
    country: 'India',
    description: 'One of the world’s oldest living cities on the sacred banks of the Ganges, famed for evening Ganga Aarti, ancient ghats, and spiritual transcendence.',
    category: 'Religious & Spiritual',
    subcategory: 'Sacred Ganges City',
    latitude: 25.3176,
    longitude: 82.9739,
    best_time_to_visit: 'October to March (Crisp dawn boat rides)',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Budget',
    travel_themes: ['Spiritual', 'Historical', 'Cultural', 'Photography', 'Food'],
    activities: ['Ganga Aarti at Dashashwamedh Ghat', 'Sunrise boat ride', 'Kashi Vishwanath Darshan', 'Banarasi silk shopping', 'Street food trail'],
    accessibility: 'Available',
    nearby_destinations: ['Sarnath', 'Prayagraj', 'Ayodhya', 'Chunar Fort'],
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-up-02',
    name: 'Ayodhya',
    state: 'Uttar Pradesh',
    district_or_city: 'Ayodhya',
    country: 'India',
    description: 'Sacred birthplace of Lord Rama on the banks of the Saryu River, home to the magnificent Shri Ram Janmabhoomi Mandir, Ram Ki Paidi, and Hanumangarhi.',
    category: 'Religious & Spiritual',
    subcategory: 'Sacred Pilgrimage City',
    latitude: 26.7922,
    longitude: 82.1998,
    best_time_to_visit: 'October to March & Diwali Deepotsav',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Budget',
    travel_themes: ['Spiritual', 'Heritage', 'Pilgrimage', 'Culture'],
    activities: ['Ram Janmabhoomi darshan', 'Saryu River evening aarti', 'Hanumangarhi visit', 'Deepotsav festival'],
    accessibility: 'Verified',
    nearby_destinations: ['Lucknow', 'Varanasi', 'Prayagraj'],
    image: 'https://images.unsplash.com/photo-1627894483216-2138af692e32?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-up-03',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    district_or_city: 'Lucknow',
    country: 'India',
    description: 'The City of Nawabs, celebrated for Awadhi culinary mastery (Galouti & Tunday Kebabs), exquisite Chikankari embroidery, and architectural marvel Bara Imambara.',
    category: 'City',
    subcategory: 'Awadhi Heritage & Culinary Hub',
    latitude: 26.8467,
    longitude: 80.9462,
    best_time_to_visit: 'October to March',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Food & Cuisine', 'Historical', 'Architecture', 'Culture'],
    activities: ['Bara & Chhota Imambara labyrinth (Bhool Bhulaiya)', 'Aminabad food trail', 'Hazratganj shopping', 'Chikankari craft tours'],
    accessibility: 'Verified',
    nearby_destinations: ['Ayodhya', 'Kanpur', 'Varanasi'],
    image: 'https://images.unsplash.com/photo-1599831104321-4f4640191834?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-up-04',
    name: 'Mathura & Vrindavan',
    state: 'Uttar Pradesh',
    district_or_city: 'Mathura',
    country: 'India',
    description: 'The divine land of Braj Bhoomi, birthplace of Lord Krishna, featuring iconic temples like Banke Bihari, Prem Mandir, Krishna Janmasthan, and famous Peda sweets.',
    category: 'Religious & Spiritual',
    subcategory: 'Krishna Pilgrimage Circuit',
    latitude: 27.4924,
    longitude: 77.6737,
    best_time_to_visit: 'October to March & Janmashtami / Holi',
    recommended_duration: '2 Days',
    budget_category: 'Budget',
    travel_themes: ['Spiritual', 'Culture', 'Festivals', 'Heritage'],
    activities: ['Banke Bihari Temple Aarti', 'Prem Mandir light show', 'Yamuna Aarti at Vishram Ghat', 'Lathmar Holi celebration'],
    accessibility: 'Available',
    nearby_destinations: ['Agra', 'Govardhan', 'Barsana', 'Delhi'],
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-hp-01',
    name: 'Manali',
    state: 'Himachal Pradesh',
    district_or_city: 'Kullu',
    country: 'India',
    description: 'High-altitude Himalayan valley retreat famed for snow-capped peaks, Solang Valley adventure sports, Rohtang Pass, Old Manali cafes, and apple orchards.',
    category: 'Mountains & Hill Stations',
    subcategory: 'Himalayan Adventure & Hill Station',
    latitude: 32.2432,
    longitude: 77.1892,
    best_time_to_visit: 'October to June (Snow sports in winter, pleasant summers)',
    recommended_duration: '4 - 5 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Adventure', 'Nature', 'Mountains', 'Relaxation', 'Winter Sports'],
    activities: ['Paragliding in Solang', 'Rohtang Pass snow drive', 'Hadimba Temple cedar walk', 'Atal Tunnel drive', 'Old Manali cafe hopping'],
    accessibility: 'Available',
    nearby_destinations: ['Kasol', 'Kullu', 'Sissu (Lahaul)', 'Naggar', 'Shimla'],
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-hp-02',
    name: 'Shimla',
    state: 'Himachal Pradesh',
    district_or_city: 'Shimla',
    country: 'India',
    description: 'The historic summer capital of British India, perched along pine ridges with colonial heritage, The Mall, Ridge promenade, and UNESCO Kalka-Shimla Toy Train.',
    category: 'Mountains & Hill Stations',
    subcategory: 'Colonial Hill Station & Toy Train',
    latitude: 31.1048,
    longitude: 77.1734,
    best_time_to_visit: 'March to June & December to February (Snowfall)',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Mountains', 'Heritage', 'Family', 'Nature', 'Romantic'],
    activities: ['Kalka-Shimla Toy Train ride', 'Mall Road evening walk', 'Jakhoo Temple ropeway', 'Kufri snow view', 'Viceregal Lodge tour'],
    accessibility: 'Verified',
    nearby_destinations: ['Kufri', 'Chail', 'Mashobra', 'Narkanda', 'Manali'],
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-hp-03',
    name: 'Kasol & Parvati Valley',
    state: 'Himachal Pradesh',
    district_or_city: 'Kullu',
    country: 'India',
    description: 'Tranquil backpacker haven along the Parvati River, surrounded by pine forests, hot springs of Manikaran, and treks to Kheerganga, Tosh, and Malana.',
    category: 'Mountains & Hill Stations',
    subcategory: 'Trekking & Hippie Mountain Valley',
    latitude: 32.0104,
    longitude: 77.315,
    best_time_to_visit: 'March to June & September to November',
    recommended_duration: '3 - 5 Days',
    budget_category: 'Budget',
    travel_themes: ['Trekking', 'Adventure', 'Nature', 'Youth & Solo', 'Cafes'],
    activities: ['Kheerganga natural hot springs trek', 'Manikaran Sahib Gurudwara dip', 'Tosh village walk', 'River cafe relaxation', 'Pin Parvati Pass trail'],
    accessibility: 'Available',
    nearby_destinations: ['Manali', 'Manikaran', 'Tosh', 'Malana', 'Jibhi'],
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-hp-04',
    name: 'Dharamshala & McLeod Ganj',
    state: 'Himachal Pradesh',
    district_or_city: 'Kangra',
    country: 'India',
    description: 'Home to His Holiness the Dalai Lama and the Tibetan Government in Exile, framed by the mighty Dhauladhar range, cedar trails, and Triund trek.',
    category: 'Mountains & Hill Stations',
    subcategory: 'Tibetan Spiritual & Mountain Haven',
    latitude: 32.219,
    longitude: 76.3234,
    best_time_to_visit: 'March to June & September to December',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Budget',
    travel_themes: ['Spiritual', 'Trekking', 'Mountains', 'Culture', 'Tibetan Food'],
    activities: ['Tsuglagkhang Complex & Dalai Lama Temple', 'Triund ridge trek', 'Bhagsunag waterfall', 'Tibetan momo & thukpa trails', 'Dharamshala cricket stadium'],
    accessibility: 'Available',
    nearby_destinations: ['Bir Billing (Paragliding)', 'Palampur', 'Kangra Fort', 'Dalhousie'],
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-uk-01',
    name: 'Rishikesh',
    state: 'Uttarakhand',
    district_or_city: 'Dehradun / Tehri Garhwal',
    country: 'India',
    description: 'The Yoga Capital of the World along the turquoise Ganges, offering holy ghats, iconic suspension bridges (Ram & Lakshman Jhula), and white-water rafting.',
    category: 'Adventure',
    subcategory: 'Yoga Capital & White-Water Rafting',
    latitude: 30.0869,
    longitude: 78.2676,
    best_time_to_visit: 'September to November & March to May',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Budget',
    travel_themes: ['Adventure', 'Spiritual', 'Wellness', 'River Sports', 'Yoga'],
    activities: ['Ganges white-water rafting (Grade III & IV)', 'Triveni Ghat Evening Aarti', 'Bungee jumping at Mohan Chatti', 'Beatles Ashram tour', 'Yoga retreats'],
    accessibility: 'Verified',
    nearby_destinations: ['Haridwar', 'Dehradun', 'Mussoorie', 'Shivpuri', 'Neelkanth Mahadev'],
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-uk-02',
    name: 'Haridwar',
    state: 'Uttarakhand',
    district_or_city: 'Haridwar',
    country: 'India',
    description: 'One of the seven sacred Sapta Puri pilgrimage sites, where the Ganges enters the Indo-Gangetic plains, renowned for Har Ki Pauri and Kumbh Mela.',
    category: 'Religious & Spiritual',
    subcategory: 'Sacred Gateway to Gods',
    latitude: 29.9457,
    longitude: 78.1642,
    best_time_to_visit: 'October to April',
    recommended_duration: '2 Days',
    budget_category: 'Budget',
    travel_themes: ['Spiritual', 'Heritage', 'Pilgrimage', 'Photography'],
    activities: ['Har Ki Pauri evening Maha Aarti', 'Mansa Devi & Chandi Devi ropeways', 'Sacred bath in holy Ganga', 'Local street sweets & kachoris'],
    accessibility: 'Verified',
    nearby_destinations: ['Rishikesh', 'Dehradun', 'Rajaji National Park'],
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-uk-03',
    name: 'Mussoorie & Nainital',
    state: 'Uttarakhand',
    district_or_city: 'Dehradun / Nainital',
    country: 'India',
    description: 'Queen of the Hills featuring Kempty Falls, George Everest peak, Lake Naini yachting, and panoramic views of the Garhwal and Kumaon Himalayas.',
    category: 'Mountains & Hill Stations',
    subcategory: 'Colonial Himalayan Resorts & Lakes',
    latitude: 30.4598,
    longitude: 78.0644,
    best_time_to_visit: 'March to June & September to November',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Mountains', 'Lakes', 'Nature', 'Romantic', 'Family'],
    activities: ['Naini Lake boating', 'Kempty Falls dip', 'Gun Hill ropeway', 'Mall Road evening walk', 'George Everest House hike'],
    accessibility: 'Verified',
    nearby_destinations: ['Dehradun', 'Dhanaulti', 'Jim Corbett', 'Ranikhet'],
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-uk-04',
    name: 'Jim Corbett National Park',
    state: 'Uttarakhand',
    district_or_city: 'Nainital',
    country: 'India',
    description: 'India’s oldest national park established in 1936, world-famous for Royal Bengal tigers, Asiatic elephants, and luxury jungle river lodges along Kosi.',
    category: 'Wildlife & Nature',
    subcategory: 'Project Tiger Reserve',
    latitude: 29.5308,
    longitude: 78.7747,
    best_time_to_visit: 'November to June (Dhikala zone opens Nov 15)',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Premium',
    travel_themes: ['Wildlife', 'Nature', 'Safari', 'Photography', 'Adventure'],
    activities: ['Open 4x4 Jeep Safari in Dhikala & Bijrani', 'Birdwatching (over 580 species)', 'Riverside luxury resort bonfire', 'Elephant spotting'],
    accessibility: 'Available',
    nearby_destinations: ['Nainital', 'Ranikhet', 'Rishikesh', 'Delhi'],
    image: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-uk-05',
    name: 'Kedarnath & Badrinath (Char Dham)',
    state: 'Uttarakhand',
    district_or_city: 'Rudraprayag / Chamoli',
    country: 'India',
    description: 'Supreme sacred Himalayan shrines nestled beneath Kedarnath Peak and Neelkanth peak, forming the core of the sacred Char Dham and Panch Kedar pilgrimage.',
    category: 'Religious & Spiritual',
    subcategory: 'High Himalayan Char Dham Pilgrimage',
    latitude: 30.7352,
    longitude: 79.0669,
    best_time_to_visit: 'May to June & September to October (Temples open Akshaya Tritiya to Diwali)',
    recommended_duration: '5 - 7 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Spiritual', 'High Altitude', 'Trekking', 'Himalayas', 'Pilgrimage'],
    activities: ['Kedarnath Temple 16km trek / helicopter ride', 'Badrinath Temple Darshan', 'Tapt Kund thermal spring bath', 'Mana last Indian village visit', 'Vasudhara Falls hike'],
    accessibility: 'Available',
    nearby_destinations: ['Rishikesh', 'Guptkashi', 'Joshimath', 'Valley of Flowers', 'Auli'],
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-jk-01',
    name: 'Srinagar & Dal Lake',
    state: 'Jammu & Kashmir (UT)',
    district_or_city: 'Srinagar',
    country: 'India',
    description: 'The crown jewel of Kashmir, renowned for intricately carved cedar houseboats on Dal Lake, floating vegetable markets, Mughal gardens, and Shikara rides.',
    category: 'Mountains & Hill Stations',
    subcategory: 'Paradise Valley & Houseboats',
    latitude: 34.0837,
    longitude: 74.7973,
    best_time_to_visit: 'April to October (Tulip gardens in April, Chinar gold in Autumn)',
    recommended_duration: '4 - 5 Days',
    budget_category: 'Premium',
    travel_themes: ['Mountains', 'Romantic', 'Culture', 'Nature', 'Houseboat Luxury'],
    activities: ['Sunset Shikara ride on Dal Lake', 'Heritage houseboat stay', 'Shalimar & Nishat Mughal Gardens', 'Pashmina & Kashmiri carpet shopping', 'Wazwan feast'],
    accessibility: 'Verified',
    nearby_destinations: ['Gulmarg', 'Pahalgam', 'Sonamarg', 'Doodhpathri'],
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-jk-02',
    name: 'Gulmarg & Pahalgam',
    state: 'Jammu & Kashmir (UT)',
    district_or_city: 'Baramulla / Anantnag',
    country: 'India',
    description: 'Meadow of Flowers featuring the world’s highest operational Gondola cable car in Gulmarg and the emerald Betaab & Aru valleys in Pahalgam.',
    category: 'Mountains & Hill Stations',
    subcategory: 'Alpine Snow Resorts & Valleys',
    latitude: 34.0484,
    longitude: 74.3805,
    best_time_to_visit: 'December to March (World-class powder snow) & May to September (Lush alpine meadows)',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Premium',
    travel_themes: ['Adventure', 'Winter Sports', 'Skiing', 'Nature', 'Mountains'],
    activities: ['Gulmarg Gondola ride to Apharwat Peak (Phase 2 - 3,980m)', 'Skiing and snowboarding', 'Pony trek in Betaab Valley & Baisaran', 'Lidder River trout fishing & rafting'],
    accessibility: 'Verified',
    nearby_destinations: ['Srinagar', 'Sonamarg', 'Aru Valley'],
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-lad-01',
    name: 'Leh Ladakh',
    state: 'Ladakh (UT)',
    district_or_city: 'Leh',
    country: 'India',
    description: 'The Land of High Mountain Passes, featuring turquoise Pangong Tso Lake, sand dunes of Nubra Valley with double-humped camels, and ancient Buddhist gompas.',
    category: 'Mountains & Hill Stations',
    subcategory: 'High Altitude Himalayan Desert',
    latitude: 34.1526,
    longitude: 77.5771,
    best_time_to_visit: 'May to September (Roads via Manali/Srinagar open)',
    recommended_duration: '6 - 8 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Adventure', 'Biking', 'Mountains', 'Spiritual', 'Photography'],
    activities: ['Pangong Tso & Tso Moriri lake camping', 'Khardung La Pass drive (5,359m)', 'Nubra Valley Bactrian camel safari', 'Thiksey & Hemis Monastery exploration', 'Magnetic Hill & Hall of Fame'],
    accessibility: 'Available',
    nearby_destinations: ['Nubra Valley', 'Pangong Tso', 'Zanskar', 'Kargil', 'Manali'],
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-pb-01',
    name: 'Amritsar (Golden Temple)',
    state: 'Punjab',
    district_or_city: 'Amritsar',
    country: 'India',
    description: 'Spiritual and cultural capital of Sikhism, home to Sri Harmandir Sahib (Golden Temple), the world’s largest community kitchen (Langar), and Wagah Border ceremony.',
    category: 'Religious & Spiritual',
    subcategory: 'Golden Temple & Patriotic Border',
    latitude: 31.62,
    longitude: 74.8765,
    best_time_to_visit: 'October to March',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Budget',
    travel_themes: ['Spiritual', 'Historical', 'Food & Cuisine', 'Patriotic'],
    activities: ['Golden Temple nighttime illumination & Palki Sahib', 'Community service at Langar', 'Wagah Border beating retreat ceremony', 'Amritsari Kulcha & Lassi feast', 'Jallianwala Bagh memorial'],
    accessibility: 'Verified',
    nearby_destinations: ['Chandigarh', 'Jalandhar', 'Dharamshala', 'Lahore Border'],
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-ch-01',
    name: 'Chandigarh',
    state: 'Chandigarh (UT)',
    district_or_city: 'Chandigarh',
    country: 'India',
    description: 'India’s premier master-planned city designed by Swiss-French architect Le Corbusier, famed for the Rock Garden, Sukhna Lake, and Zakir Hussain Rose Garden.',
    category: 'City',
    subcategory: 'Modernist Planned City & Architecture',
    latitude: 30.7333,
    longitude: 76.7794,
    best_time_to_visit: 'October to March',
    recommended_duration: '2 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Architecture', 'Urban Life', 'Gardens', 'Food'],
    activities: ['Nek Chand Rock Garden sculpture walk', 'Sukhna Lake sunset boating', 'Capitol Complex UNESCO tour', 'Sector 17 & 8 dining'],
    accessibility: 'Verified',
    nearby_destinations: ['Shimla', 'Kasauli', 'Pinjore Gardens', 'Amritsar'],
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },

  // --- WEST INDIA ---
  {
    id: 'ind-rj-01',
    name: 'Jaipur (The Pink City)',
    state: 'Rajasthan',
    district_or_city: 'Jaipur',
    country: 'India',
    description: 'UNESCO World Heritage royal capital of Rajasthan, celebrated for Amer Fort, Hawa Mahal honeycomb palace, City Palace, Jantar Mantar, and vibrant bazaars.',
    category: 'Historical & Heritage',
    subcategory: 'Royal Forts & UNESCO Pink City',
    latitude: 26.9124,
    longitude: 75.7873,
    best_time_to_visit: 'October to March',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Historical', 'Architecture', 'Shopping', 'Culinary', 'Royal Luxury'],
    activities: ['Elephant / Jeep ride up Amer Fort', 'Hawa Mahal & City Palace photography', 'Johari Bazaar gem shopping', 'Authentic Dal Baati Churma feast', 'Chokhi Dhani village experience'],
    accessibility: 'Verified',
    nearby_destinations: ['Pushkar', 'Ajmer', 'Ranthambore', 'Agra', 'Delhi'],
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-rj-02',
    name: 'Udaipur (City of Lakes)',
    state: 'Rajasthan',
    district_or_city: 'Udaipur',
    country: 'India',
    description: 'The Venice of the East, famed for Lake Pichola, the majestic City Palace complex, Jag Mandir island palace, Lake Palace, and romantic sunset boat cruises.',
    category: 'Historical & Heritage',
    subcategory: 'Romantic Lake City & Palaces',
    latitude: 24.5854,
    longitude: 73.7125,
    best_time_to_visit: 'October to March',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Premium',
    travel_themes: ['Romantic', 'Palaces', 'Lakes', 'Historical', 'Fine Dining'],
    activities: ['Lake Pichola sunset boat ride', 'City Palace & Crystal Gallery tour', 'Bagore Ki Haveli Dharohar dance show', 'Monsoon Palace hill drive', 'Saheliyon Ki Bari stroll'],
    accessibility: 'Verified',
    nearby_destinations: ['Kumbhalgarh Fort', 'Ranakpur Jain Temples', 'Mount Abu', 'Chittorgarh Fort'],
    image: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-rj-03',
    name: 'Jodhpur (The Blue City)',
    state: 'Rajasthan',
    district_or_city: 'Jodhpur',
    country: 'India',
    description: 'The Sun City dominated by the colossal Mehrangarh Fort rising 400 feet above indigo-blue painted Brahmin houses, stepwells, and Umaid Bhawan Palace.',
    category: 'Historical & Heritage',
    subcategory: 'Blue City & Forts',
    latitude: 26.2389,
    longitude: 73.0243,
    best_time_to_visit: 'October to March',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Historical', 'Architecture', 'Photography', 'Heritage'],
    activities: ['Mehrangarh Fort audio tour & zip-lining (Flying Fox)', 'Toorji Ka Jhalra stepwell walk', 'Blue city photography walk', 'Makhaniya Lassi & Pyaaz Kachori'],
    accessibility: 'Verified',
    nearby_destinations: ['Jaisalmer', 'Udaipur', 'Osian Desert Dunes', 'Pushkar'],
    image: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-rj-04',
    name: 'Jaisalmer (The Golden City)',
    state: 'Rajasthan',
    district_or_city: 'Jaisalmer',
    country: 'India',
    description: 'Golden sandstone fortress in the heart of the Great Thar Desert, famed for the living Jaisalmer Fort (Sonar Qila), Sam Sand Dunes, and desert camel safaris.',
    category: 'Historical & Heritage',
    subcategory: 'Thar Desert & Living Fort',
    latitude: 26.9157,
    longitude: 70.9083,
    best_time_to_visit: 'October to March (Desert Festival in Feb)',
    recommended_duration: '3 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Desert Safari', 'Historical', 'Camping', 'Culture', 'Adventure'],
    activities: ['Sam Sand Dunes camel safari & dune bashing', 'Luxury Swiss desert tent camping with Kalbelia folk dance', 'Jaisalmer Fort walk', 'Patwon Ki Haveli architecture'],
    accessibility: 'Available',
    nearby_destinations: ['Jodhpur', 'Kuldhara Ghost Village', 'Longewala Border Post', 'Bikaner'],
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-rj-05',
    name: 'Ranthambore National Park',
    state: 'Rajasthan',
    district_or_city: 'Sawai Madhopur',
    country: 'India',
    description: 'Premier wildlife park famous for daytime sightings of Royal Bengal tigers roaming among ancient 10th-century fort ruins and banyan trees.',
    category: 'Wildlife & Nature',
    subcategory: 'Bengal Tiger Sanctuary & Fort',
    latitude: 26.0173,
    longitude: 76.5026,
    best_time_to_visit: 'October to June (Closed July-Sept monsoon)',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Premium',
    travel_themes: ['Wildlife', 'Tiger Safari', 'Photography', 'Heritage'],
    activities: ['Morning & afternoon Gypsy/Canter safaris', 'Ranthambore Fort hike', 'Padam Talao lake birdwatching', 'Luxury heritage palace stays'],
    accessibility: 'Available',
    nearby_destinations: ['Jaipur', 'Agra', 'Sawai Madhopur'],
    image: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-mh-01',
    name: 'Mumbai',
    state: 'Maharashtra',
    district_or_city: 'Mumbai / Mumbai Suburban',
    country: 'India',
    description: 'The Financial Capital of India and City of Dreams, boasting Gateway of India, Marine Drive Queen’s Necklace, Bollywood, Elephanta Caves, and vibrant nightlife.',
    category: 'City',
    subcategory: 'Cosmopolitan Megacity & Coast',
    latitude: 18.922,
    longitude: 72.8347,
    best_time_to_visit: 'October to March (Pleasant coastal breezes)',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Mid-range',
    travel_themes: ['City Life', 'Food & Cuisine', 'Heritage', 'Nightlife', 'Coast'],
    activities: ['Marine Drive sunset stroll', 'Gateway of India & Taj Mahal Palace tour', 'Elephanta Caves ferry', 'Chowpatty street food (Vada Pav, Pav Bhaji, Bhel Puri)', 'Bandra boutique & cafe trail'],
    accessibility: 'Verified',
    nearby_destinations: ['Lonavala', 'Alibaug', 'Matheran', 'Pune', 'Goa'],
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-mh-02',
    name: 'Ajanta & Ellora Caves',
    state: 'Maharashtra',
    district_or_city: 'Chhatrapati Sambhajinagar (Aurangabad)',
    country: 'India',
    description: 'UNESCO World Heritage rock-cut cave monuments featuring ancient Buddhist murals (Ajanta) and the monolithic Kailash Temple carved from a single basalt cliff (Ellora).',
    category: 'Historical & Heritage',
    subcategory: 'UNESCO Rock-Cut Cave Temples',
    latitude: 20.0268,
    longitude: 75.178,
    best_time_to_visit: 'October to March',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Archaeology', 'Historical', 'Spiritual', 'Sculpture'],
    activities: ['Kailash Temple monolithic marvel tour', 'Ajanta ancient Buddhist fresco viewing', 'Bibi Ka Maqbara visit', 'Daulatabad Fort climb'],
    accessibility: 'Available',
    nearby_destinations: ['Shirdi', 'Nashik', 'Pune', 'Mumbai'],
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-mh-03',
    name: 'Pune & Western Ghats Forts',
    state: 'Maharashtra',
    district_or_city: 'Pune',
    country: 'India',
    description: 'Cultural capital of Maharashtra surrounded by historic Maratha hill fortresses of Chhatrapati Shivaji Maharaj (Sinhagad, Raigad, Shivneri, Rajgad, Torna).',
    category: 'City',
    subcategory: 'Maratha Heritage & Fort Trekking',
    latitude: 18.5204,
    longitude: 73.8567,
    best_time_to_visit: 'July to February (Monsoon waterfalls & cool winters)',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Budget',
    travel_themes: ['Forts', 'Trekking', 'Cultural', 'Food & Cuisine', 'Nature'],
    activities: ['Sinhagad Fort trek & Kanda Bhaji feast', 'Shaniwar Wada palace tour', 'Aga Khan Palace visit', 'Lonavala & Khandala waterfall drives', 'FC Road street shopping & cafes'],
    accessibility: 'Verified',
    nearby_destinations: ['Lonavala', 'Mahabaleshwar', 'Lavasa', 'Alibaug', 'Mumbai'],
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-mh-04',
    name: 'Nashik & Shirdi',
    state: 'Maharashtra',
    district_or_city: 'Nashik / Ahmednagar',
    country: 'India',
    description: 'The Wine Capital of India situated along the Godavari River, Trimbakeshwar Jyotirlinga, Sula Vineyards, and the revered Sai Baba Samadhi Temple in Shirdi.',
    category: 'Religious & Spiritual',
    subcategory: 'Spiritual Jyotirlinga & Vineyard Country',
    latitude: 19.9975,
    longitude: 73.7898,
    best_time_to_visit: 'October to March (Grape harvesting Jan-Mar)',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Spiritual', 'Wine Tourism', 'Nature', 'Heritage'],
    activities: ['Sula & York Vineyard wine tasting and estate tour', 'Trimbakeshwar Jyotirlinga Darshan', 'Shirdi Sai Baba Temple visit', 'Panchavati & Ramkund ghat walk'],
    accessibility: 'Verified',
    nearby_destinations: ['Mumbai', 'Pune', 'Bhandardara', 'Igatpuri'],
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-goa-01',
    name: 'Goa',
    state: 'Goa',
    district_or_city: 'North Goa / South Goa',
    country: 'India',
    description: 'India’s premier coastal paradise, famed for golden sandy beaches, vibrant shacks, UNESCO Old Goa Portuguese basilicas, spice plantations, and nightlife.',
    category: 'Beaches & Coastal',
    subcategory: 'Coastal Paradise & Heritage',
    latitude: 15.2993,
    longitude: 74.124,
    best_time_to_visit: 'November to March',
    recommended_duration: '4 - 6 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Beaches', 'Nightlife', 'Seafood', 'Water Sports', 'Portuguese Heritage'],
    activities: ['Beach hopping (Baga, Calangute, Palolem, Anjuna, Morjim)', 'Fort Aguada & Chapora sunset', 'Basilica of Bom Jesus tour', 'Fontainhas Latin Quarter walk', 'Mandovi River sunset cruise'],
    accessibility: 'Verified',
    nearby_destinations: ['Gokarna', 'Dudhsagar Falls', 'Hampi', 'Kolhapur', 'Karwar'],
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-gj-01',
    name: 'Gir National Park & Somnath',
    state: 'Gujarat',
    district_or_city: 'Gir Somnath',
    country: 'India',
    description: 'The exclusive worldwide natural sanctuary of the majestic Asiatic Lion, coupled with the sacred oceanfront Somnath Jyotirlinga Temple.',
    category: 'Wildlife & Nature',
    subcategory: 'Asiatic Lion Reserve & Jyotirlinga',
    latitude: 21.1241,
    longitude: 70.8242,
    best_time_to_visit: 'December to March',
    recommended_duration: '3 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Wildlife', 'Safari', 'Spiritual', 'Coast'],
    activities: ['Open Jeep Safari in Sasan Gir', 'Somnath Temple Sound & Light show', 'Diu Island Portuguese fort visit', 'Kathiyawadi Thali feast'],
    accessibility: 'Available',
    nearby_destinations: ['Diu', 'Dwarka', 'Junagadh', 'Rajkot'],
    image: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-gj-02',
    name: 'Rann of Kutch (White Desert)',
    state: 'Gujarat',
    district_or_city: 'Kutch',
    country: 'India',
    description: 'The world’s largest salt desert shimmering under the full moon, celebrated during the vibrant Rann Utsav with luxury tent cities, Kutchi handicrafts, and folk music.',
    category: 'Wildlife & Nature',
    subcategory: 'White Salt Desert & Cultural Festival',
    latitude: 23.8344,
    longitude: 69.8329,
    best_time_to_visit: 'November to February (Rann Utsav season)',
    recommended_duration: '3 Days',
    budget_category: 'Premium',
    travel_themes: ['Desert', 'Cultural', 'Festivals', 'Handicrafts', 'Photography'],
    activities: ['Full moon walk on White Rann salt flats', 'Dhordo Tent City cultural shows', 'Kala Dungar (Black Hill) sunset', 'Rogan art & Rogan handicraft village tours', 'Dholavira Harappan UNESCO site visit'],
    accessibility: 'Verified',
    nearby_destinations: ['Bhuj', 'Dholavira', 'Mandvi Beach', 'Ahmedabad'],
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-gj-03',
    name: 'Statue of Unity & Ahmedabad',
    state: 'Gujarat',
    district_or_city: 'Narmada / Ahmedabad',
    country: 'India',
    description: 'The world’s tallest statue at 182 meters honoring Sardar Vallabhbhai Patel, and UNESCO World Heritage City Ahmedabad with Sabarmati Ashram and Stepwells.',
    category: 'Historical & Heritage',
    subcategory: 'Colossal Monument & UNESCO Heritage City',
    latitude: 21.838,
    longitude: 73.7191,
    best_time_to_visit: 'October to March',
    recommended_duration: '3 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Monuments', 'Architecture', 'History', 'Food'],
    activities: ['Statue of Unity viewing gallery (153m)', 'Valley of Flowers & Laser show', 'Sabarmati Ashram visit', 'Adalaj Stepwell photography', 'Manek Chowk midnight food market'],
    accessibility: 'Verified',
    nearby_destinations: ['Vadodara', 'Champaner-Pavagadh', 'Modhera Sun Temple', 'Patan Rani Ki Vav'],
    image: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1000&q=80',
  },

  // --- EAST INDIA ---
  {
    id: 'ind-wb-01',
    name: 'Kolkata (City of Joy)',
    state: 'West Bengal',
    district_or_city: 'Kolkata',
    country: 'India',
    description: 'Cultural capital of India, renowned for colonial Victoria Memorial, Howrah Bridge, iconic yellow Ambassador cabs, artistic soul, Durga Puja, and legendary street food.',
    category: 'City',
    subcategory: 'Cultural Capital & Colonial Architecture',
    latitude: 22.5726,
    longitude: 88.3639,
    best_time_to_visit: 'October to March & Durga Puja (Sept/Oct)',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Budget',
    travel_themes: ['Cultural', 'Historical', 'Food & Cuisine', 'Literature', 'Art'],
    activities: ['Victoria Memorial & Maidan stroll', 'Howrah Bridge & ferry crossing on Hooghly', 'Park Street dining & Flurys tea', 'College Street Boi Para book market', 'Authentic sweets (Rosogolla, Sandesh, Mishti Doi)'],
    accessibility: 'Verified',
    nearby_destinations: ['Sundarbans', 'Darjeeling', 'Digha', 'Shantiniketan', 'Bishnupur'],
    image: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-wb-02',
    name: 'Darjeeling',
    state: 'West Bengal',
    district_or_city: 'Darjeeling',
    country: 'India',
    description: 'Queen of the Hills in the Eastern Himalayas, famed for world-renowned Champagne of Teas, UNESCO Toy Train, Tiger Hill sunrise over Mt. Kanchenjunga, and monasteries.',
    category: 'Mountains & Hill Stations',
    subcategory: 'Himalayan Tea Estates & Toy Train',
    latitude: 27.041,
    longitude: 88.2663,
    best_time_to_visit: 'March to May & October to December',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Mountains', 'Tea Tourism', 'Nature', 'Heritage', 'Toy Train'],
    activities: ['Tiger Hill dawn sunrise over Kanchenjunga (8,586m)', 'UNESCO Darjeeling Himalayan Railway joyride', 'Happy Valley Tea Estate tour', 'Batasia Loop & War Memorial', 'Glenary’s bakery & Keventers breakfast'],
    accessibility: 'Available',
    nearby_destinations: ['Gangtok', 'Kalimpong', 'Mirik', 'Pelling', 'Siliguri'],
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-wb-03',
    name: 'Sundarbans National Park',
    state: 'West Bengal',
    district_or_city: 'South 24 Parganas',
    country: 'India',
    description: 'The world’s largest mangrove forest and delta Biosphere Reserve, home to the Royal Bengal tiger, saltwater crocodiles, and river dolphin boat safaris.',
    category: 'Wildlife & Nature',
    subcategory: 'UNESCO Mangrove Tiger Delta',
    latitude: 21.9497,
    longitude: 88.9007,
    best_time_to_visit: 'September to March',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Wildlife', 'Eco-Tourism', 'Boat Safari', 'Nature'],
    activities: ['Sajnekhali watchtower tiger spotting', 'Mangrove creek motorized boat cruise', 'Dobanki canopy walk', 'Village honey-collector cultural interaction'],
    accessibility: 'Available',
    nearby_destinations: ['Kolkata', 'Bakkhali', 'Digha'],
    image: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-od-01',
    name: 'Puri & Konark Sun Temple',
    state: 'Odisha',
    district_or_city: 'Puri',
    country: 'India',
    description: 'Sacred coastal Char Dham holy city of Lord Jagannath, coupled with the UNESCO World Heritage 13th-century stone chariot Konark Sun Temple and Golden Beach.',
    category: 'Religious & Spiritual',
    subcategory: 'Char Dham Ocean Pilgrimage & Sun Temple',
    latitude: 19.8135,
    longitude: 85.8312,
    best_time_to_visit: 'October to March (Ratha Yatra in June/July)',
    recommended_duration: '3 Days',
    budget_category: 'Budget',
    travel_themes: ['Spiritual', 'UNESCO Heritage', 'Beaches', 'Architecture', 'Culture'],
    activities: ['Jagannath Temple Mahaprasad tasting', 'Konark Sun Temple stone wheel architecture tour', 'Blue Flag certified Golden Beach walk', 'Chilika Lake Irrawaddy dolphin boat cruise', 'Raghurajpur Pattachitra artisan village'],
    accessibility: 'Verified',
    nearby_destinations: ['Bhubaneswar', 'Chilika Lake', 'Gopalpur', 'Cuttack'],
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-br-01',
    name: 'Bodh Gaya & Nalanda',
    state: 'Bihar',
    district_or_city: 'Gaya / Nalanda',
    country: 'India',
    description: 'The supreme cradle of Buddhism where Prince Siddhartha attained enlightenment beneath the sacred Bodhi Tree, and the world’s ancient Nalanda University ruins.',
    category: 'Religious & Spiritual',
    subcategory: 'UNESCO Buddhist Enlightenment & Ancient University',
    latitude: 24.6959,
    longitude: 84.9914,
    best_time_to_visit: 'October to March',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Budget',
    travel_themes: ['Spiritual', 'UNESCO Heritage', 'Archaeology', 'Peace & Meditation'],
    activities: ['Mahabodhi Temple meditation beneath Bodhi Tree', 'Giant 80-foot Buddha statue photography', 'International monasteries tour', 'Nalanda Mahavihara university excavation walk', 'Rajgir Vishwa Shanti Stupa ropeway'],
    accessibility: 'Verified',
    nearby_destinations: ['Rajgir', 'Gaya', 'Patna', 'Varanasi'],
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1000&q=80',
  },

  // --- NORTHEAST INDIA ---
  {
    id: 'ind-sk-01',
    name: 'Gangtok',
    state: 'Sikkim',
    district_or_city: 'East Sikkim',
    country: 'India',
    description: 'The enchanting Himalayan capital of Sikkim, perched on mountain ridges overlooking Mt. Kanchenjunga with Buddhist monasteries, MG Marg, and alpine lakes.',
    category: 'Mountains & Hill Stations',
    subcategory: 'Himalayan Capital & Monasteries',
    latitude: 27.3389,
    longitude: 88.6065,
    best_time_to_visit: 'March to June (Flowers & clear peaks) & October to December',
    recommended_duration: '4 - 5 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Mountains', 'Nature', 'Culture', 'Lakes', 'Adventure'],
    activities: ['Tsomgo (Changu) Lake & Baba Mandir excursion', 'Nathula Pass Indo-China border drive (14,140ft)', 'Rumtek Monastery bell chanting', 'MG Marg vehicle-free stroll', 'Ban Jhakri & Seven Sister waterfalls'],
    accessibility: 'Verified',
    nearby_destinations: ['Pelling', 'Lachung', 'Yumthang Valley', 'Ravangla', 'Darjeeling'],
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-sk-02',
    name: 'North Sikkim (Yumthang Valley & Gurudongmar Lake)',
    state: 'Sikkim',
    district_or_city: 'North Sikkim',
    country: 'India',
    description: 'High-altitude wonderland featuring the sacred turquoise Gurudongmar Lake at 17,800 ft, hot springs, and Yumthang Valley of Rhododendron Flowers.',
    category: 'Mountains & Hill Stations',
    subcategory: 'High Alpine Valleys & Sacred Lakes',
    latitude: 27.9158,
    longitude: 88.7189,
    best_time_to_visit: 'April to June (Rhododendron blooms) & October to December',
    recommended_duration: '3 Days',
    budget_category: 'Mid-range',
    travel_themes: ['High Altitude', 'Valley of Flowers', 'Lakes', 'Adventure'],
    activities: ['Gurudongmar Lake high-altitude excursion', 'Yumthang Valley flower trails', 'Zero Point snow touch', 'Lachung & Lachen mountain homestays'],
    accessibility: 'Available',
    nearby_destinations: ['Gangtok', 'Pelling', 'Ravangla'],
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-mg-01',
    name: 'Shillong & Cherrapunji (Sohra)',
    state: 'Meghalaya',
    district_or_city: 'East Khasi Hills',
    country: 'India',
    description: 'The Scotland of the East and wettest realm on Earth, celebrated for living double-decker root bridges, Nohkalikai Falls, crystal Dawki river, and Mawlynnong clean village.',
    category: 'Wildlife & Nature',
    subcategory: 'Living Root Bridges & Waterfalls',
    latitude: 25.5788,
    longitude: 91.8933,
    best_time_to_visit: 'September to May',
    recommended_duration: '4 - 5 Days',
    budget_category: 'Budget',
    travel_themes: ['Nature', 'Waterfalls', 'Trekking', 'Eco-Tourism', 'Mountains'],
    activities: ['Nongriat Double Decker Living Root Bridge trek', 'Dawki Umngot crystal river boating', 'Nohkalikai & Wei Sawdong tiered waterfall hikes', 'Mawsmai & Arwah limestone cave caving', 'Mawlynnong Asia’s cleanest village walk'],
    accessibility: 'Available',
    nearby_destinations: ['Guwahati', 'Kaziranga', 'Jowai'],
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-as-01',
    name: 'Kaziranga National Park & Guwahati',
    state: 'Assam',
    district_or_city: 'Golaghat / Nagaon / Kamrup',
    country: 'India',
    description: 'UNESCO World Heritage wildlife sanctuary hosting two-thirds of the world’s Great One-Horned Rhinoceros population along the mighty Brahmaputra river.',
    category: 'Wildlife & Nature',
    subcategory: 'One-Horned Rhino Sanctuary',
    latitude: 26.5775,
    longitude: 93.1711,
    best_time_to_visit: 'November to April',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Wildlife', 'Rhino Safari', 'Tea Plantations', 'Spiritual'],
    activities: ['Central & Western range Elephant & Jeep safaris', 'Kamakhya Temple Shakti Peeth darshan', 'Brahmaputra sunset river cruise', 'Assam Orthodox Tea garden tasting'],
    accessibility: 'Verified',
    nearby_destinations: ['Shillong', 'Majuli Island', 'Manas National Park', 'Tezpur'],
    image: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-ar-01',
    name: 'Tawang',
    state: 'Arunachal Pradesh',
    district_or_city: 'Tawang',
    country: 'India',
    description: 'Spectacular high-altitude monastery fortress in the Eastern Himalayas at 10,000 ft, home to India’s largest monastery (Tawang Gompa), Sela Pass, and Madhuri Lake.',
    category: 'Mountains & Hill Stations',
    subcategory: 'Monasteries & High Passes',
    latitude: 27.5861,
    longitude: 91.8594,
    best_time_to_visit: 'March to June & September to November',
    recommended_duration: '4 - 5 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Mountains', 'Spiritual', 'Biking', 'Lakes', 'Himalayas'],
    activities: ['Tawang Monastery (Galden Namgey Lhatse) tour', 'Sela Pass snow gateway (13,700ft)', 'Sangetsar (Madhuri) Lake visit', 'Nuranang (Jang) Falls photography', 'Jaswant Garh war memorial tribute'],
    accessibility: 'Available',
    nearby_destinations: ['Dirang', 'Bomdila', 'Guwahati', 'Tezpur'],
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80',
  },

  // --- SOUTH INDIA ---
  {
    id: 'ind-ka-01',
    name: 'Bengaluru (Bangalore)',
    state: 'Karnataka',
    district_or_city: 'Bengaluru Urban',
    country: 'India',
    description: 'The Silicon Valley and Garden City of India, celebrated for pleasant year-round weather, craft microbreweries, Lalbagh Botanical Garden, and tech innovation.',
    category: 'City',
    subcategory: 'Tech Hub, Gardens & Craft Breweries',
    latitude: 12.9716,
    longitude: 77.5946,
    best_time_to_visit: 'October to March (Pleasant all year)',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Mid-range',
    travel_themes: ['City Life', 'Breweries', 'Food & Cuisine', 'Gardens', 'Tech'],
    activities: ['Lalbagh Botanical Garden Glass House walk', 'Indiranagar & Koramangala craft brewery trail', 'Bengaluru Palace tour', 'Vidyarthi Bhavan Benne Masala Dosa breakfast', 'Cubbon Park morning run'],
    accessibility: 'Verified',
    nearby_destinations: ['Mysuru', 'Coorg', 'Nandi Hills', 'Kabini', 'Chikmagalur'],
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-ka-02',
    name: 'Mysuru (Mysore)',
    state: 'Karnataka',
    district_or_city: 'Mysuru',
    country: 'India',
    description: 'City of Palaces, world-renowned for the magnificent illuminated Mysore Palace, Dasara royal celebrations, Ashtanga yoga, sandalwood, and Mysore Pak sweets.',
    category: 'Historical & Heritage',
    subcategory: 'Royal Palaces & Silk Capital',
    latitude: 12.2958,
    longitude: 76.6394,
    best_time_to_visit: 'October to March (Grand Dasara in Oct)',
    recommended_duration: '2 - 3 Days',
    budget_category: 'Budget',
    travel_themes: ['Palaces', 'Historical', 'Culture', 'Shopping', 'Sweets'],
    activities: ['Mysore Palace grand illumination (100,000 bulbs on Sundays)', 'Chamundi Hill temple climb', 'Devaraja Market spice & flower walk', 'Mysore Pak sweet tasting', 'Brindavan Gardens musical fountain'],
    accessibility: 'Verified',
    nearby_destinations: ['Coorg', 'Kabini', 'Bandipur', 'Bengaluru', 'Srirangapatna'],
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-ka-03',
    name: 'Hampi',
    state: 'Karnataka',
    district_or_city: 'Vijayanagara',
    country: 'India',
    description: 'UNESCO World Heritage open-air museum of giant boulder hills and ruins of the 14th-century Vijayanagara Empire, featuring the Stone Chariot and Virupaksha Temple.',
    category: 'Historical & Heritage',
    subcategory: 'UNESCO Boulder Ruins & Vijayanagara Capital',
    latitude: 15.335,
    longitude: 76.46,
    best_time_to_visit: 'October to March',
    recommended_duration: '3 Days',
    budget_category: 'Budget',
    travel_themes: ['UNESCO Heritage', 'Archaeology', 'Bouldering', 'Biking', 'Sunset'],
    activities: ['Vittala Temple Stone Chariot & musical pillars', 'Virupaksha Temple sunset climb at Matanga Hill', 'Coracle boat ride on Tungabhadra River', 'Hippie Island bicycle exploration', 'Lotus Mahal & Elephant Stables'],
    accessibility: 'Available',
    nearby_destinations: ['Badami', 'Aihole', 'Pattadakal', 'Goa', 'Bengaluru'],
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-ka-04',
    name: 'Coorg (Kodagu) & Gokarna',
    state: 'Karnataka',
    district_or_city: 'Kodagu / Uttara Kannada',
    country: 'India',
    description: 'The Scotland of India with coffee plantations and Abbey Falls (Coorg), alongside the pristine Om Beach and Mahabaleshwar temple coast (Gokarna).',
    category: 'Beaches & Coastal',
    subcategory: 'Coffee Plantations & Serene Beaches',
    latitude: 12.4244,
    longitude: 75.7382,
    best_time_to_visit: 'October to March',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Coffee Estates', 'Nature', 'Beaches', 'Trekking', 'Relaxation'],
    activities: ['Coorg private coffee estate walk & tasting', 'Namdroling Golden Temple Tibetan monastery', 'Om Beach & Kudle Beach trekking', 'Abbey & Iruppu waterfalls', 'Authentic Pandi Curry & Akki Roti feast'],
    accessibility: 'Verified',
    nearby_destinations: ['Mysuru', 'Chikmagalur', 'Goa', 'Murudeshwar'],
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-kl-01',
    name: 'Kerala (Munnar & Alleppey / Kochi)',
    state: 'Kerala',
    district_or_city: 'Alappuzha / Idukki / Ernakulam',
    country: 'India',
    description: 'God’s Own Country, famed for overnight luxury houseboats on tranquil backwaters (Alleppey), mist-covered emerald tea plantations (Munnar), and Fort Kochi heritage.',
    category: 'Wildlife & Nature',
    subcategory: 'Backwaters, Houseboats & Tea Hills',
    latitude: 9.9312,
    longitude: 76.2673,
    best_time_to_visit: 'September to March',
    recommended_duration: '5 - 7 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Backwaters', 'Houseboats', 'Nature', 'Ayurveda', 'Tea Gardens'],
    activities: ['Private houseboat cruise on Vembanad Lake', 'Munnar Kolukkumalai tea plantation safari', 'Fort Kochi Chinese Fishing Nets & Jew Town', 'Kathakali cultural dance performance', 'Ayurvedic wellness rejuvenation'],
    accessibility: 'Verified',
    nearby_destinations: ['Varkala', 'Wayanad', 'Thekkady (Periyar)', 'Kovalam', 'Athirappilly'],
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-kl-02',
    name: 'Varkala & Kovalam',
    state: 'Kerala',
    district_or_city: 'Thiruvananthapuram',
    country: 'India',
    description: 'Spectacular red laterite cliffs rising above the Arabian Sea at Papanasam Beach, seaside yoga shacks, lighthouse panoramas, and fresh coastal seafood.',
    category: 'Beaches & Coastal',
    subcategory: 'Red Cliffs, Surfing & Yoga',
    latitude: 8.7379,
    longitude: 76.7163,
    best_time_to_visit: 'October to March',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Budget',
    travel_themes: ['Beaches', 'Cliffs', 'Yoga', 'Surfing', 'Relaxation'],
    activities: ['Varkala Cliff promenade sunset dinner', 'Surfing lessons at Black Beach', 'Kovalam Lighthouse 360-degree viewpoint', 'Padmanabhaswamy Temple darshan in Trivandrum', 'Janardhana Swamy ancient temple'],
    accessibility: 'Verified',
    nearby_destinations: ['Thiruvananthapuram', 'Alleppey', 'Kanyakumari', 'Jatayu Earth Center'],
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-tn-01',
    name: 'Chennai & Mahabalipuram (Mamallapuram)',
    state: 'Tamil Nadu',
    district_or_city: 'Chennai / Chengalpattu',
    country: 'India',
    description: 'Gateway to South India featuring Marina Beach, Carnatic music traditions, and UNESCO 7th-century rock-cut Shore Temple and monolithic stone chariots.',
    category: 'City',
    subcategory: 'UNESCO Shore Temples & Carnatic Heritage',
    latitude: 13.0827,
    longitude: 80.2707,
    best_time_to_visit: 'November to February',
    recommended_duration: '3 Days',
    budget_category: 'Budget',
    travel_themes: ['UNESCO Heritage', 'Culture', 'Temples', 'Food & Filter Coffee', 'Coast'],
    activities: ['Shore Temple & Arjuna’s Penance bas-relief tour', 'Marina Beach sunset walk', 'Kapaleeshwarar Temple Dravidian gopuram', 'Authentic South Indian Thali & Filter Coffee', 'Puducherry French colony excursion'],
    accessibility: 'Verified',
    nearby_destinations: ['Pondicherry (Puducherry)', 'Kanchipuram (Silk City)', 'Madurai', 'Tirupati'],
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-tn-02',
    name: 'Madurai & Rameswaram',
    state: 'Tamil Nadu',
    district_or_city: 'Madurai / Ramanathapuram',
    country: 'India',
    description: 'The historic Temple City famed for the colossal Meenakshi Amman Temple, alongside holy Rameswaram Island with the 1,000-pillar corridor and Dhanushkodi ghost town.',
    category: 'Religious & Spiritual',
    subcategory: 'Dravidian Gopurams & Sacred Sea Bridge',
    latitude: 9.9252,
    longitude: 78.1198,
    best_time_to_visit: 'October to March',
    recommended_duration: '3 - 4 Days',
    budget_category: 'Budget',
    travel_themes: ['Spiritual', 'Dravidian Architecture', 'Culture', 'Food', 'Islands'],
    activities: ['Meenakshi Amman Temple nighttime ceremonies', 'Pamban Sea Bridge scenic train crossing', 'Ramanathaswamy Temple 22 holy water wells', 'Dhanushkodi Ram Setu point safari', 'Jigarthanda cold drink & Madurai Bun Parotta'],
    accessibility: 'Verified',
    nearby_destinations: ['Kanyakumari', 'Thanjavur (Brihadeeswarar Temple)', 'Chettinad', 'Kodaikanal'],
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-tg-01',
    name: 'Hyderabad (City of Pearls)',
    state: 'Telangana',
    district_or_city: 'Hyderabad',
    country: 'India',
    description: 'The City of Nizams, world-famous for Hyderabadi Dum Biryani, historic Charminar, Golconda Fort with acoustic wonders, and royal Chowmahalla Palace.',
    category: 'City',
    subcategory: 'Nizami Heritage & World-Famous Biryani',
    latitude: 17.385,
    longitude: 78.4867,
    best_time_to_visit: 'October to March',
    recommended_duration: '3 Days',
    budget_category: 'Mid-range',
    travel_themes: ['Food & Cuisine', 'Historical', 'Architecture', 'Pearls & Shopping'],
    activities: ['Charminar & Laad Bazaar pearl shopping', 'Golconda Fort acoustic & light show', 'Chowmahalla Palace & Nizam vintage car collection', 'Authentic Hyderabadi Mutton Dum Biryani & Irani Chai with Osmania biscuits', 'Ramoji Film City full day tour'],
    accessibility: 'Verified',
    nearby_destinations: ['Warangal', 'Nagarjuna Sagar', 'Bidar', 'Bengaluru'],
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
  {
    id: 'ind-ap-01',
    name: 'Tirupati (Tirumala Balaji) & Visakhapatnam',
    state: 'Andhra Pradesh',
    district_or_city: 'Tirupati / Visakhapatnam',
    country: 'India',
    description: 'The world’s most visited sacred pilgrimage shrine atop the seven hills of Seshachalam (Sri Venkateswara Swamy), alongside Vizag’s coastal beaches and Araku Valley coffee hills.',
    category: 'Religious & Spiritual',
    subcategory: 'Supreme Balaji Pilgrimage & Coastal City',
    latitude: 13.6288,
    longitude: 79.4192,
    best_time_to_visit: 'October to March',
    recommended_duration: '3 Days',
    budget_category: 'Budget',
    travel_themes: ['Spiritual', 'Beaches', 'Pilgrimage', 'Hills', 'Culture'],
    activities: ['Tirumala Balaji Temple Darshan & Laddu Prasadam', 'Vizag RK Beach & INS Kursura Submarine Museum', 'Araku Valley Borra Caves & coffee plantations', 'Rishikonda beach water sports'],
    accessibility: 'Verified',
    nearby_destinations: ['Chennai', 'Vijayawada', 'Srikalahasti', 'Pondicherry'],
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'ind-an-01',
    name: 'Andaman & Nicobar Islands (Havelock & Neil)',
    state: 'Andaman and Nicobar Islands (UT)',
    district_or_city: 'South Andaman',
    country: 'India',
    description: 'Pristine tropical archipelago featuring Radhanagar Beach (Asia’s top beach), vibrant coral reef scuba diving, bioluminescence night kayaking, and Cellular Jail memorial.',
    category: 'Beaches & Coastal',
    subcategory: 'Tropical Island Scuba & Coral Paradise',
    latitude: 11.9761,
    longitude: 92.9876,
    best_time_to_visit: 'October to May',
    recommended_duration: '5 - 7 Days',
    budget_category: 'Premium',
    travel_themes: ['Islands', 'Scuba Diving', 'Beaches', 'Water Sports', 'Honeymoon'],
    activities: ['Radhanagar Beach sunset & Elephant Beach water sports', 'Scuba diving & snorkeling in live coral reefs', 'Night kayaking amidst bioluminescent waters', 'Cellular Jail light and sound show in Port Blair', 'Sea walk & glass bottom boat ride'],
    accessibility: 'Verified',
    nearby_destinations: ['Port Blair', 'Neil Island', 'Baratang Island (Mud Volcanoes)'],
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
    is_state_capital: true,
  },
];

/**
 * Intelligent Multi-Tier Search for India:
 * Matches cities, states, attractions, themes, keywords, and natural language queries.
 */
export function searchIndianLocations(query: string): IndianLocationResult[] {
  if (!query || !query.trim()) {
    return CORE_INDIAN_DESTINATIONS;
  }

  const rawQ = query.trim();
  const q = rawQ.toLowerCase();

  // Strict check: If user typed international keyword, return zero results
  if (!isIndianLocation(rawQ)) {
    return [];
  }

  const results: Array<{ item: IndianLocationResult; score: number }> = [];

  // Match against Core Curated Destinations
  for (const loc of CORE_INDIAN_DESTINATIONS) {
    let score = 0;
    const name = loc.name.toLowerCase();
    const state = loc.state.toLowerCase();
    const city = loc.district_or_city.toLowerCase();
    const desc = loc.description.toLowerCase();
    const cat = loc.category.toLowerCase();
    const themes = loc.travel_themes.map((t) => t.toLowerCase());
    const activities = loc.activities.map((a) => a.toLowerCase());

    if (name === q) score += 100;
    else if (name.startsWith(q)) score += 80;
    else if (name.includes(q)) score += 50;

    if (state.includes(q)) score += 40;
    if (city.includes(q)) score += 40;
    if (cat.includes(q)) score += 30;

    // Natural queries: e.g. "forts in maharashtra", "beaches in goa", "places near gangtok"
    const words = q.split(/\s+/).filter((w) => !['in', 'near', 'from', 'to', 'the', 'best', 'places', 'trips', 'trip', 'weekend'].includes(w));
    let matchedWords = 0;
    for (const w of words) {
      if (
        name.includes(w) ||
        state.includes(w) ||
        city.includes(w) ||
        desc.includes(w) ||
        cat.includes(w) ||
        themes.some((t) => t.includes(w)) ||
        activities.some((a) => a.includes(w))
      ) {
        matchedWords++;
      }
    }
    if (words.length > 0 && matchedWords === words.length) {
      score += 45 * matchedWords;
    }

    if (score > 0) {
      results.push({ item: loc, score });
    }
  }

  // Also match dynamically against all 28 States dataset
  for (const stateObj of ALL_INDIA_STATES) {
    const sName = stateObj.name.toLowerCase();
    const sDesc = stateObj.description.toLowerCase();
    const sCap = stateObj.capital.toLowerCase();

    // Check if query is targeting this state or its destinations
    for (const dest of stateObj.destinations) {
      const dName = dest.name.toLowerCase();
      const dCity = dest.city_district.toLowerCase();
      const dType = dest.type.toLowerCase();
      const dDesc = dest.description.toLowerCase();

      // Check if already in results
      const alreadyIn = results.some(
        (r) => r.item.name.toLowerCase() === dName || r.item.id === `state-dest-${dest.id}`
      );
      if (alreadyIn) continue;

      let score = 0;
      if (dName === q) score += 95;
      else if (dName.startsWith(q)) score += 75;
      else if (dName.includes(q)) score += 45;

      if (sName.includes(q) || dCity.includes(q)) score += 35;
      if (dType.includes(q)) score += 25;

      const words = q.split(/\s+/).filter((w) => !['in', 'near', 'from', 'to', 'the', 'best', 'places', 'trips', 'trip'].includes(w));
      let matchedWords = 0;
      for (const w of words) {
        if (dName.includes(w) || sName.includes(w) || dCity.includes(w) || dType.includes(w) || dDesc.includes(w)) {
          matchedWords++;
        }
      }
      if (words.length > 0 && matchedWords === words.length) {
        score += 35 * matchedWords;
      }

      if (score > 0) {
        results.push({
          score,
          item: {
            id: `state-dest-${dest.id}`,
            name: dest.name,
            state: stateObj.name,
            district_or_city: dest.city_district,
            country: 'India',
            description: dest.description,
            category: (dest.type as any) || 'Historical & Heritage',
            subcategory: `${dest.type} in ${stateObj.name}`,
            latitude: dest.latitude,
            longitude: dest.longitude,
            best_time_to_visit: dest.best_time || stateObj.best_seasons,
            recommended_duration: dest.recommended_duration || '2 - 3 Days',
            budget_category: dest.budget_category || 'Mid-range',
            travel_themes: stateObj.popular_themes,
            activities: dest.attractions.map((a) => a.name),
            accessibility: dest.accessibility,
            nearby_destinations: stateObj.destinations.filter((d) => d.id !== dest.id).slice(0, 4).map((d) => d.name),
            image: dest.image || stateObj.cover_image,
          },
        });
      }
    }
  }

  // Sort by match score descending
  results.sort((a, b) => b.score - a.score);

  return results.map((r) => r.item);
}

/**
 * Fast Autocomplete Suggester for Search Inputs across India
 */
export function getIndianLocationSuggestions(query: string, limit: number = 8): Array<{
  id: string;
  name: string;
  subtitle: string;
  category: string;
  state: string;
}> {
  if (!query || !query.trim() || !isIndianLocation(query)) {
    return [];
  }

  const matches = searchIndianLocations(query);
  return matches.slice(0, limit).map((m) => ({
    id: m.id,
    name: m.name,
    subtitle: `${m.district_or_city}, ${m.state}`,
    category: m.category,
    state: m.state,
  }));
}
